// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOBC4hhqtovS_JLlw1DC90uixQzoGN5NU',
    appId: '1:1077873090577:web:07b9e59ee6048a0337d1b0',
    messagingSenderId: '1077873090577',
    projectId: 'kshieldauth',
    authDomain: 'kshieldauth.firebaseapp.com',
    storageBucket: 'kshieldauth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnh0weHBwJ_zO9kgKL1GCx1y0qnujz5QA',
    appId: '1:1077873090577:android:6fe89d34813f32c637d1b0',
    messagingSenderId: '1077873090577',
    projectId: 'kshieldauth',
    storageBucket: 'kshieldauth.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOBC4hhqtovS_JLlw1DC90uixQzoGN5NU',
    appId: '1:1077873090577:web:e74403800363540037d1b0',
    messagingSenderId: '1077873090577',
    projectId: 'kshieldauth',
    authDomain: 'kshieldauth.firebaseapp.com',
    storageBucket: 'kshieldauth.firebasestorage.app',
  );
}
